---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Values.app_name }}
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: "0.75"   # The percentage of busy runners at which the number of desired runners are re-evaluated to scale up
    scaleDownThreshold: "0.3"  # The percentage of busy runners at which the number of desired runners are re-evaluated to scale down
    scaleUpAdjustment: 1       # The scale up runner count added to desired count
    scaleDownAdjustment: 1     # The scale down runner count subtracted from the desired count
  
